import 'package:flutter/material.dart';

import '../../tasks/domain/task_models.dart';

class ServiceEntry {
  const ServiceEntry({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.tagline,
    required this.icon,
    required this.gradient,
    required this.taskType,
    required this.ctaLabel,
    required this.suggestedTitle,
    required this.suggestedDescription,
    required this.scenes,
    required this.steps,
    required this.highlights,
  });

  final String id;
  final String title;
  final String subtitle;
  final String tagline;
  final IconData icon;
  final List<Color> gradient;
  final TaskType taskType;
  final String ctaLabel;
  final String suggestedTitle;
  final String suggestedDescription;
  final List<String> scenes;
  final List<String> steps;
  final List<String> highlights;
}

const serviceCatalog = <ServiceEntry>[
  ServiceEntry(
    id: 'express',
    title: '快递代取',
    subtitle: '驿站、快递柜，帮你拿到楼下',
    tagline: '不方便下楼时，让同小区邻居顺路取件。',
    icon: Icons.inventory_2_rounded,
    gradient: [Color(0xFF00509E), Color(0xFF00509E)],
    taskType: TaskType.packagePickup,
    ctaLabel: '发布快递代取',
    suggestedTitle: '北门驿站快递代取',
    suggestedDescription: '帮我从驿站取一个小件，送到楼下电梯厅即可。',
    scenes: ['驿站高峰排队', '快递柜距楼栋较近', '晚间归楼顺路带回'],
    steps: ['填写取件信息与交付位置', '系统自动估算服务费用', '接单后同步履约状态'],
    highlights: ['支持履约凭证上传', '适合高频短距离场景', '默认进入托管结算流程'],
  ),
  ServiceEntry(
    id: 'food',
    title: '外卖代拿',
    subtitle: '骑手到楼下，顺手带上楼',
    tagline: '开会、带娃或走不开时，不用让外卖一直等。',
    icon: Icons.ramen_dining_rounded,
    gradient: [Color(0xFFE03C31), Color(0xFFE03C31)],
    taskType: TaskType.packagePickup,
    ctaLabel: '发布外卖代拿',
    suggestedTitle: '楼下外卖代拿',
    suggestedDescription: '骑手到了楼下，帮忙带上来，送到门口即可。',
    scenes: ['午休不便离开', '会议期间无法接单', '雨天减少往返'],
    steps: ['选择服务类型', '补充楼栋与楼层信息', '到达后由发布者确认完成'],
    highlights: ['适合同楼顺带处理', '支持角色上下文切换', '状态卡在消息页同步'],
  ),
  ServiceEntry(
    id: 'soy',
    title: '酱油速购',
    subtitle: '日用品、饮料，顺路带回',
    tagline: '楼下小店就能买到的东西，交给顺路的人。',
    icon: Icons.local_grocery_store_rounded,
    gradient: [Color(0xFFFFD100), Color(0xFFFFD100)],
    taskType: TaskType.errand,
    ctaLabel: '发布酱油速购',
    suggestedTitle: '楼下便利店酱油速购',
    suggestedDescription: '顺手买抽纸、矿泉水和生活补给，送到电梯口即可。',
    scenes: ['便利店补货', '饮品顺购', '夜间生活补给'],
    steps: ['描述采购清单', '系统估算服务费用', '完成后进入托管结算'],
    highlights: ['覆盖多类即时采购需求', '适合临时小件采购', '支持实时加价补差'],
  ),
  ServiceEntry(
    id: 'errand',
    title: '万能帮办',
    subtitle: '打印、拿东西、送钥匙都能发',
    tagline: '说清楚要办的事、地点和时间，就能找人帮忙。',
    icon: Icons.handshake_rounded,
    gradient: [Color(0xFF00509E), Color(0xFF00509E)],
    taskType: TaskType.errand,
    ctaLabel: '发布万能帮办',
    suggestedTitle: '打印材料顺手带回',
    suggestedDescription: '帮忙打印一份纸质材料并送至楼下前台，文件可提前发送。',
    scenes: ['打印点取件', '资料交接', '临时送钥匙'],
    steps: ['填写详细说明', '根据重量与楼层估价', '接单后进入履约流程'],
    highlights: ['适配复杂说明场景', '支持楼层与天气加价', '适合灵活型协作需求'],
  ),
  ServiceEntry(
    id: 'pool',
    title: '社区拼单',
    subtitle: '一起下单，少付配送费',
    tagline: '早餐、晚饭、生鲜和零食，都能和邻居凑一单。',
    icon: Icons.group_work_rounded,
    gradient: [Color(0xFFFFD100), Color(0xFFFFD100)],
    taskType: TaskType.pool,
    ctaLabel: '发起社区拼单',
    suggestedTitle: '晚饭轻食拼单',
    suggestedDescription: '邀请同楼用户一起拼单，配送费均摊后统一送达。',
    scenes: ['晚饭轻食拼单', '早餐团购', '夜间零食补给'],
    steps: ['发起拼单主题', '邻居加入分摊配送费', '满员后统一成团配送'],
    highlights: ['支持动态分摊运费', '团满后自动更新状态', '前端大厅直接展示进度'],
  ),
  ServiceEntry(
    id: 'pet',
    title: '宠物照看',
    subtitle: '喂养、遛宠、添水，按时来',
    tagline: '临时回不来，让附近熟悉宠物的人照看一会儿。',
    icon: Icons.pets_rounded,
    gradient: [Color(0xFFE03C31), Color(0xFFE03C31)],
    taskType: TaskType.errand,
    ctaLabel: '发布宠物照看',
    suggestedTitle: '傍晚遛狗 15 分钟',
    suggestedDescription: '今天晚饭前帮忙遛一下狗，楼下小区内即可。',
    scenes: ['短时遛宠', '加班喂猫', '外出期间代添水'],
    steps: ['填写宠物习惯', '约定时间和地点', '完成后互评积累信用'],
    highlights: ['更重视信任关系', '建议优先同楼用户', '可配合社区认证信息'],
  ),
  ServiceEntry(
    id: 'mutual',
    title: '邻里协同',
    subtitle: '借物、看包裹、到点提醒',
    tagline: '不用跑腿的小事，也能在邻里间找到回应。',
    icon: Icons.diversity_3_rounded,
    gradient: [Color(0xFF00509E), Color(0xFF00509E)],
    taskType: TaskType.errand,
    ctaLabel: '发布协同请求',
    suggestedTitle: '帮忙看一下门口包裹',
    suggestedDescription: '我晚点回去，先帮我看一下门口包裹是否送到。',
    scenes: ['临时借雨伞', '顺手看包裹', '到点提醒取件'],
    steps: ['简短描述需求', '设置感谢金或协作方式', '完成后留下评价'],
    highlights: ['适合轻量协同事项', '支持低价或零价发布', '突出社区信任关系'],
  ),
  ServiceEntry(
    id: 'recycle',
    title: '代扔垃圾',
    subtitle: '顺路下楼，帮你带走一袋',
    tagline: '垃圾已经打包好，找一位正好下楼的邻居。',
    icon: Icons.delete_outline_rounded,
    gradient: [Color(0xFFE03C31), Color(0xFFE03C31)],
    taskType: TaskType.errand,
    ctaLabel: '发布代扔需求',
    suggestedTitle: '顺手代扔垃圾',
    suggestedDescription: '垃圾已打包好，帮忙下楼顺手带到投放点。',
    scenes: ['临时不便下楼', '夜间减少往返', '手持物品较多'],
    steps: ['写明垃圾类型', '补充楼层信息', '跑者顺路处理后确认'],
    highlights: ['高频轻量、门槛低', '适合顺路处理', '费用结构简单直观'],
  ),
  ServiceEntry(
    id: 'print',
    title: '打印取件',
    subtitle: '打印、复印、资料代拿',
    tagline: '文件先发给打印店，再请人把纸质材料送回来。',
    icon: Icons.print_rounded,
    gradient: [Color(0xFF00509E), Color(0xFF00509E)],
    taskType: TaskType.errand,
    ctaLabel: '发布打印需求',
    suggestedTitle: '楼宇打印资料取回',
    suggestedDescription: '帮忙去打印店取回资料，送到宿舍楼下。',
    scenes: ['临时打印材料', '复印证件', '楼宇资料代拿'],
    steps: ['填写资料说明', '约定交接位置', '接单后实时沟通进度'],
    highlights: ['适合办公与居住混合场景', '可与万能帮办共用流程', '表达成本低'],
  ),
  ServiceEntry(
    id: 'more',
    title: '其他需求',
    subtitle: '没找到分类，也可以直接发布',
    tagline: '把需要帮忙的事情写清楚，附近的人就能看见。',
    icon: Icons.apps_rounded,
    gradient: [Color(0xFFFFD100), Color(0xFFFFD100)],
    taskType: TaskType.errand,
    ctaLabel: '查看全部能力',
    suggestedTitle: '社区综合帮办',
    suggestedDescription: '需要一个灵活的综合协助场景，欢迎顺手接力。',
    scenes: ['统一查看服务目录', '快速定位合适入口', '了解平台能力边界'],
    steps: ['浏览服务分类', '选择合适入口', '按统一任务或拼单流程发起'],
    highlights: ['覆盖 8 个核心模块', '便于快速理解平台能力', '可持续扩展更多场景'],
  ),
];
