spring:
  datasource:
    url: jdbc:h2:mem:community_micro_logistics;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: warn

server:
  address: 0.0.0.0

app:
  auth:
    otp:
      expose-code: true
